### PR TITLE
added(NFT Detail): Updated Market detail page

### PR DESCRIPTION
**Pull request by Ash-Ch**
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

### CODE REVIEW

**Comment by crackaf** [comment]
@Arbab10042 This is two days old, and why it is not closed or merged? Created by @Ash-Ch after #7 on 4th Jan. And we have 7 more commits after this PR!!

**Comment by Arbab10042** [comment]
> 



> @Arbab10042 This is two days old, and why it is not closed or merged? Created by @Ash-Ch after #7 on 4th Jan. And we have 7 more commits after this PR!!

I thought you merged it

**Comment by crackaf** [comment]
I merged #7 and closed #6. I wasn't told about this PR. I think @Ash-Ch created two PR's that day and I was told about only one.

**Comment by crackaf** [comment]
Merged it. As it didn't have any conflicts.

**Comment by Ash-Ch** [comment]
> @Arbab10042 This is two days old, and why it is not closed or merged? Created by @Ash-Ch after #7 on 4th Jan. And we have 7 more commits after this PR!!

I was waiting for you guys to merge it coz I did this on Tuesday before taking leave so I wanted to save my last work, as a backup I stored those files separately as well coz I was kind of sure that you guys will do this .

**Comment by crackaf** [comment]
There were eslint errors. @Arbab10042 had to spend time on your code to resolve those. `yarn lint` OR `npm lint` will show those errors.

**Pull request merged**
